replicaCount: 2

image:
  repository: api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: gateway.localhost
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true

monolithUri: http://ticketmonster.ticket-monster.svc.cluster.local:8082

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
