namespace: observability
domain: example.com

image:
  repository: grafana/grafana
  tag: 12.4.4

adminUser: admin
adminSecretName: grafana-credentials
adminPasswordKey: admin-password

storage: 5Gi

port: 3000

subPath: /panel

auth:
  oauthEnabled: true
  oauthAutoLogin: false
  oauthAllowSignUp: true
  oauthScopes: "openid email profile"
  oauthRoleAttributePath: "contains(realm_access.roles[*], 'ADMIN') && 'Admin' || 'Editor'"
  keycloakRealm: ticket-monster
  keycloakInternalUrl: "http://keycloak.infrastructure.svc.cluster.local:8080/auth"

datasources: |
  apiVersion: 1

  datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      access: proxy
      url: http://prometheus.observability.svc.cluster.local:9090
      isDefault: true
      editable: true

    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki.observability.svc.cluster.local:3100
      editable: true
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: "trace_id=(\\w+)"
            name: TraceID
            url: "$${__value.raw}"

    - name: Tempo
      type: tempo
      uid: tempo
      access: proxy
      url: http://tempo.observability.svc.cluster.local:3200
      editable: true
      jsonData:
        httpMethod: POST
        serviceMap:
          datasourceUid: prometheus
