replicaCount: 2

image:
  repository: ticketmonster
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

ingress:
  enabled: true
  className: nginx
  host: api.localhost
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env:
  POSTGRES_HOST: postgresql.infrastructure.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: ticketmonster
  MONGO_HOST: mongodb.infrastructure.svc.cluster.local
  MONGO_PORT: "27017"
  MONGO_DB: ticketmonster_catalog
  REDIS_HOST: redis-master.infrastructure.svc.cluster.local
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: redpanda.infrastructure.svc.cluster.local:9092
  KEYCLOAK_ISSUER_URI: http://keycloak.infrastructure.svc.cluster.local:8080/realms/ticket-monster
  RESERVATION_SCHEMA: reservation
  PAYMENT_SCHEMA: payment
