apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: ticketmonster
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ticketmonster
  template:
    metadata:
      labels:
        app: ticketmonster
    spec:
      containers:
        - name: ticketmonster
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: postgresql-credentials
            - secretRef:
                name: mongodb-credentials
            - secretRef:
                name: redis-credentials
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
