apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-rate-limit
spec:
  rateLimit:
    average: {{ .Values.rateLimit.average }}
    burst: {{ .Values.rateLimit.burst }}
    period: {{ .Values.rateLimit.period }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-secure-headers
spec:
  headers:
    customFrameOptionsValue: SAMEORIGIN
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: same-origin
    customResponseHeaders:
      X-Content-Type-Options: nosniff
