apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
      name: http
    - port: {{ .Values.otlpGrpcPort }}
      targetPort: {{ .Values.otlpGrpcPort }}
      name: otlp-grpc
    - port: {{ .Values.otlpHttpPort }}
      targetPort: {{ .Values.otlpHttpPort }}
      name: otlp-http
  selector:
    app: tempo
